# Generated by Django 5.2.4 on 2025-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_teacherreport_class_assigned_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherreport',
            name='period',
            field=models.IntegerField(),
        ),
    ]
