# Generated by Django 5.2.4 on 2025-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_teacherreport_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherreport',
            name='approved',
        ),
        migrations.AddField(
            model_name='teacherreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
